/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framework.structureData;

/**
 *
 * @author gbarbieri
 */
public class LimitsData {

    public int MAX_COMPUTE_SHADER_STORAGE_BLOCKS;
    public int MAX_COMPUTE_UNIFORM_BLOCKS;
    public int MAX_COMPUTE_TEXTURE_IMAGE_UNITS;
    public int MAX_COMPUTE_IMAGE_UNIFORMS;
    public int MAX_COMPUTE_UNIFORM_COMPONENTS;
    public int MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS;
    public int MAX_COMPUTE_ATOMIC_COUNTERS;
    public int MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS;
    public int MAX_COMPUTE_SHARED_MEMORY_SIZE;
    public int MAX_COMPUTE_WORK_GROUP_INVOCATIONS;
    public int MAX_COMPUTE_WORK_GROUP_COUNT;
    public int MAX_COMPUTE_WORK_GROUP_SIZE;

    public int MAX_VERTEX_ATOMIC_COUNTERS;
    public int MAX_VERTEX_SHADER_STORAGE_BLOCKS;
    public int MAX_VERTEX_ATTRIBS;
    public int MAX_VERTEX_OUTPUT_COMPONENTS;
    public int MAX_VERTEX_TEXTURE_IMAGE_UNITS;
    public int MAX_VERTEX_UNIFORM_COMPONENTS;
    public int MAX_VERTEX_UNIFORM_VECTORS;
    public int MAX_VERTEX_UNIFORM_BLOCKS;
    public int MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS;

    public int MAX_TESS_CONTROL_ATOMIC_COUNTERS;
    public int MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS;
    public int MAX_TESS_CONTROL_INPUT_COMPONENTS;
    public int MAX_TESS_CONTROL_OUTPUT_COMPONENTS;
    public int MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS;
    public int MAX_TESS_CONTROL_UNIFORM_BLOCKS;
    public int MAX_TESS_CONTROL_UNIFORM_COMPONENTS;
    public int MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS;

    public int MAX_TESS_EVALUATION_ATOMIC_COUNTERS;
    public int MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS;
    public int MAX_TESS_EVALUATION_INPUT_COMPONENTS;
    public int MAX_TESS_EVALUATION_OUTPUT_COMPONENTS;
    public int MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS;
    public int MAX_TESS_EVALUATION_UNIFORM_BLOCKS;
    public int MAX_TESS_EVALUATION_UNIFORM_COMPONENTS;
    public int MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS;

    public int MAX_GEOMETRY_ATOMIC_COUNTERS;
    public int MAX_GEOMETRY_SHADER_STORAGE_BLOCKS;
    public int MAX_GEOMETRY_INPUT_COMPONENTS;
    public int MAX_GEOMETRY_OUTPUT_COMPONENTS;
    public int MAX_GEOMETRY_TEXTURE_IMAGE_UNITS;
    public int MAX_GEOMETRY_UNIFORM_BLOCKS;
    public int MAX_GEOMETRY_UNIFORM_COMPONENTS;
    public int MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS;
    public int MAX_VERTEX_STREAMS;

    public int MAX_FRAGMENT_ATOMIC_COUNTERS;
    public int MAX_FRAGMENT_SHADER_STORAGE_BLOCKS;
    public int MAX_FRAGMENT_INPUT_COMPONENTS;
    public int MAX_FRAGMENT_UNIFORM_COMPONENTS;
    public int MAX_FRAGMENT_UNIFORM_VECTORS;
    public int MAX_FRAGMENT_UNIFORM_BLOCKS;
    public int MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS;
    public int MAX_DRAW_BUFFERS;
    public int MAX_DUAL_SOURCE_DRAW_BUFFERS;

    public int MAX_COLOR_ATTACHMENTS;
    public int MAX_FRAMEBUFFER_WIDTH;
    public int MAX_FRAMEBUFFER_HEIGHT;
    public int MAX_FRAMEBUFFER_LAYERS;
    public int MAX_FRAMEBUFFER_SAMPLES;
    public int MAX_SAMPLE_MASK_WORDS;

    public int MAX_TRANSFORM_FEEDBACK_BUFFERS;
    public int MIN_MAP_BUFFER_ALIGNMENT;

    public int MAX_TEXTURE_IMAGE_UNITS;
    public int MAX_COMBINED_TEXTURE_IMAGE_UNITS;
    public int MAX_RECTANGLE_TEXTURE_SIZE;
    public int MAX_DEEP_3D_TEXTURE_WIDTH_HEIGHT_NV;
    public int MAX_DEEP_3D_TEXTURE_DEPTH_NV;
    public int MAX_COLOR_TEXTURE_SAMPLES;
    public int MAX_DEPTH_TEXTURE_SAMPLES;
    public int MAX_INTEGER_SAMPLES;
    public int MAX_TEXTURE_BUFFER_SIZE;
    public int NUM_COMPRESSED_TEXTURE_FORMATS;
    public int MAX_TEXTURE_MAX_ANISOTROPY_EXT;

    public int MAX_PATCH_VERTICES;
    public int MAX_TESS_GEN_LEVEL;
    public int MAX_SUBROUTINES;
    public int MAX_SUBROUTINE_UNIFORM_LOCATIONS;
    public int MAX_COMBINED_ATOMIC_COUNTERS;
    public int MAX_COMBINED_SHADER_STORAGE_BLOCKS;
    public int MAX_PROGRAM_TEXEL_OFFSET;
    public int MIN_PROGRAM_TEXEL_OFFSET;
    public int MAX_COMBINED_UNIFORM_BLOCKS;
    public int MAX_UNIFORM_BUFFER_BINDINGS;
    public int MAX_UNIFORM_BLOCK_SIZE;
    public int MAX_UNIFORM_LOCATIONS;
    public int MAX_VARYING_COMPONENTS;
    public int MAX_VARYING_VECTORS;
    public int MAX_VARYING_FLOATS;
    public int MAX_SHADER_STORAGE_BUFFER_BINDINGS;
    public int MAX_SHADER_STORAGE_BLOCK_SIZE;
    public int MAX_COMBINED_SHADER_OUTPUT_RESOURCES;
    public int SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT;
    public int UNIFORM_BUFFER_OFFSET_ALIGNMENT;
    public int NUM_PROGRAM_BINARY_FORMATS;
    public int PROGRAM_BINARY_FORMATS;
    public int NUM_SHADER_BINARY_FORMATS;
    public int SHADER_BINARY_FORMATS;
}
